// <auto-generated />
using System;
using Envios.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Envios.Infrastructure.Migrations
{
    [DbContext(typeof(EnviosDbContext))]
    partial class EnviosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Envios.Domain.Entities.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DireccionSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaEntregado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEstimada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuiaPaqueteria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("IdOrden")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreRepartidor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("ENV_Envio", (string)null);
                });

            modelBuilder.Entity("Envios.Domain.Entities.HistorialRastreo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEnvio")
                        .HasColumnType("uuid");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("NuevaFechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdEnvio");

                    b.ToTable("ENV_HistorialRastreo", (string)null);
                });

            modelBuilder.Entity("Envios.Domain.Entities.HistorialRastreo", b =>
                {
                    b.HasOne("Envios.Domain.Entities.Envio", null)
                        .WithMany("HistorialRastros")
                        .HasForeignKey("IdEnvio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Envios.Domain.Entities.Envio", b =>
                {
                    b.Navigation("HistorialRastros");
                });
#pragma warning restore 612, 618
        }
    }
}
