version: '3.8'
services:

  envios-db:
    image: postgres:17
    container_name: envios-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: EnviosDB
    ports:
      - "5433:5432"
    volumes:
      - envios-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  envios-api:
    build:
      context: .
      dockerfile: Envios.API/Dockerfile
    container_name: envios-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__EnviosDB=Host=envios-db;Port=5432;Database=EnviosDB;Username=postgres;Password=admin
    depends_on:
      envios-db:
        condition: service_healthy

  promociones-db:
    image: postgres:17
    container_name: promociones-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: PromocionesDB
    ports:
      - "5434:5432"
    volumes:
      - promociones-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  promociones-api:
    build:
      context: .
      dockerfile: Promociones.API/Dockerfile
    container_name: promociones-api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PromocionesDB=Host=promociones-db;Port=5432;Database=PromocionesDB;Username=postgres;Password=admin
    depends_on:
      promociones-db:
        condition: service_healthy

volumes:
  envios-data:
  promociones-data: