// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promociones.Infrastructure;

#nullable disable

namespace Promociones.Infrastructure.Migrations
{
    [DbContext(typeof(PromocionesDbContext))]
    partial class PromocionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promociones.Domain.Entities.Promocion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsIndefinido")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontoMinimoCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NombreCampana")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.ToTable("PRO_Descuento", (string)null);
                });

            modelBuilder.Entity("Promociones.Domain.Entities.PromocionMSI", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BancosParticipantes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("IdPromocionDescuento")
                        .HasColumnType("uuid");

                    b.Property<int>("Meses")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoMinimoCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPromocionDescuento");

                    b.ToTable("PRO_PromocionMSI", (string)null);
                });

            modelBuilder.Entity("Promociones.Domain.Entities.ReglaCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCategoriaCatalogo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPromocionDescuento")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PorcentajeAplicable")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPromocionDescuento", "IdCategoriaCatalogo")
                        .IsUnique();

                    b.ToTable("PRO_ReglaCategoria", (string)null);
                });

            modelBuilder.Entity("Promociones.Domain.Entities.PromocionMSI", b =>
                {
                    b.HasOne("Promociones.Domain.Entities.Promocion", null)
                        .WithMany("OpcionesMSI")
                        .HasForeignKey("IdPromocionDescuento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promociones.Domain.Entities.ReglaCategoria", b =>
                {
                    b.HasOne("Promociones.Domain.Entities.Promocion", null)
                        .WithMany("ReglasCategorias")
                        .HasForeignKey("IdPromocionDescuento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promociones.Domain.Entities.Promocion", b =>
                {
                    b.Navigation("OpcionesMSI");

                    b.Navigation("ReglasCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
